name: hello-world

on: push

jobs:
  hello-world-job:

    # ubuntu linux virtual machine running the action hosted by github
    runs-on: ubuntu-latest
  
    steps:
      - name: check out repository code
        uses: actions/checkout@v4
      - run: echo "$(cat hello_world.txt)"
